apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infra-portal
  namespace: argocd
spec:
  description: Infrastructure Provisioning Portal
  sourceRepos:
    - "https://github.com/pavan-nagula/Infra-Portal-GitOps.git"
  destinations:
    - namespace: infra-portal
      server: https://kubernetes.default.svc
    - namespace: infra-portal-dev
      server: https://kubernetes.default.svc
    - namespace: infra-portal-staging
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
  namespaceResourceWhitelist:
    - group: ""
      kind: "*"
    - group: apps
      kind: "*"
    - group: networking.k8s.io
      kind: "*"
    - group: autoscaling
      kind: "*"
