apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-portal-dev
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: infra-portal
    environment: local
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infra-portal

  sources:
    - repoURL: https://github.com/pavan-nagula/Infra-Portal-GitOps.git
      targetRevision: main
      path: charts/infra-portal
      helm:
        releaseName: infra-portal
        valueFiles:
          - $values/environments/local/infra-portal/values.yaml
    - repoURL: https://github.com/pavan-nagula/Infra-Portal-GitOps.git
      targetRevision: main
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: infra-portal-dev

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PruneLast=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
