apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "infra-portal.fullname" . }}-backend
  labels:
    {{- include "infra-portal.backend.labels" . | nindent 4 }}
data:
  ENV: {{ .Values.backend.env | default "production" | quote }}
  APP_NAME: {{ .Values.backend.appName | default "infra-portal" | quote }}
  CORS_ALLOWED_ORIGINS: {{ .Values.backend.corsAllowedOrigins | quote }}
  SECURITY_ENABLED: {{ .Values.backend.securityEnabled | default "true" | quote }}
  TERRAFORM_REPO_PATH: {{ .Values.backend.terraformRepoPath | default "" | quote }}
  GITHUB_ORG: {{ .Values.backend.githubOrg | default "cubic-aws" | quote }}
  GITHUB_REPO: {{ .Values.backend.githubRepo | default "terraform-cts-umb-internal" | quote }}
  GITHUB_BASE_BRANCH: {{ .Values.backend.githubBaseBranch | default "main" | quote }}
  ARGOCD_GITHUB_ORG: {{ .Values.backend.argocdGithubOrg | default "cubic-aws" | quote }}
  ARGOCD_GITHUB_REPO: {{ .Values.backend.argocdGithubRepo | default "argocd-cts-umb-app-of-apps" | quote }}
  ARGOCD_GITHUB_BASE_BRANCH: {{ .Values.backend.argocdGithubBaseBranch | default "gotham" | quote }}
  RATE_LIMIT_PER_MINUTE: {{ .Values.backend.rateLimitPerMinute | default "60" | quote }}
