apiVersion: v1
kind: Secret
metadata:
  name: {{ include "infra-portal.fullname" . }}-backend-secrets
  labels:
    {{- include "infra-portal.backend.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-delete-policy: before-hook-creation
type: Opaque
data:
  {{- if .Values.backend.secrets.githubToken }}
  github-token: {{ .Values.backend.secrets.githubToken | b64enc | quote }}
  {{- else }}
  github-token: {{ "" | b64enc | quote }}
  {{- end }}
  {{- if .Values.backend.secrets.apiKey }}
  api-key: {{ .Values.backend.secrets.apiKey | b64enc | quote }}
  {{- else }}
  api-key: {{ "" | b64enc | quote }}
  {{- end }}
