apiVersion: v1
kind: Service
metadata:
  name: {{ include "infra-portal.fullname" . }}-backend
  labels:
    {{- include "infra-portal.backend.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8000
      targetPort: http
      protocol: TCP
  selector:
    {{- include "infra-portal.backend.selectorLabels" . | nindent 4 }}
